import { Team, Player, Match, User } from '@/types';

const RAW_TEAMS: Team[] = [
  // ==========================================
  // CATEGORÍA: ABIERTA VARONES (13 Equipos)
  // ==========================================
  {
    id: 'team-ab-1',
    name: 'Leones Q',
    shortName: 'Leones Q',
    category: 'Abierta Varones',
    logo: 'shield',
    primaryColor: '#EA580C',
    secondaryColor: '#FFFFFF',
    delegate: 'Dr. Santiago Morales',
    phone: '0991112233',
  },
  {
    id: 'team-ab-2',
    name: 'Futleg',
    shortName: 'Futleg',
    category: 'Abierta Varones',
    logo: 'gavel',
    primaryColor: '#0284C7',
    secondaryColor: '#FFFFFF',
    delegate: 'Ab. Mateo Benítez',
    phone: '0992223344',
  },
  {
    id: 'team-ab-3',
    name: 'Abogadasos',
    shortName: 'Abogadasos',
    category: 'Abierta Varones',
    logo: 'scale',
    primaryColor: '#00A859',
    secondaryColor: '#FFFFFF',
    delegate: 'Dr. Fernando Salazar',
    phone: '0993334455',
  },
  {
    id: 'team-ab-4',
    name: 'AKD',
    shortName: 'AKD Abierta',
    category: 'Abierta Varones',
    logo: 'crown',
    primaryColor: '#DC2626',
    secondaryColor: '#FBBF24',
    delegate: 'Ab. Christian Medina',
    phone: '0994445566',
  },
  {
    id: 'team-ab-5',
    name: 'Camaradas',
    shortName: 'Camaradas',
    category: 'Abierta Varones',
    logo: 'landmark',
    primaryColor: '#4F46E5',
    secondaryColor: '#FFFFFF',
    delegate: 'Dr. Hugo Ramos',
    phone: '0995556677',
  },
  {
    id: 'team-ab-6',
    name: 'Sport Legal',
    shortName: 'Sport Legal',
    category: 'Abierta Varones',
    logo: 'trophy',
    primaryColor: '#D97706',
    secondaryColor: '#FFFFFF',
    delegate: 'Ab. Esteban Naranjo',
    phone: '0996667788',
  },
  {
    id: 'team-ab-7',
    name: 'Alianza Legal',
    shortName: 'Alianza Legal',
    category: 'Abierta Varones',
    logo: 'book',
    primaryColor: '#1E3A8A',
    secondaryColor: '#93C5FD',
    delegate: 'Dr. Byron López',
    phone: '0997778899',
  },
  {
    id: 'team-ab-8',
    name: 'Boman Legal',
    shortName: 'Boman Legal',
    category: 'Abierta Varones',
    logo: 'file-text',
    primaryColor: '#047857',
    secondaryColor: '#FFFFFF',
    delegate: 'Ab. Andrés Sevilla',
    phone: '0998889900',
  },
  {
    id: 'team-ab-9',
    name: 'Club IDUS',
    shortName: 'IDUS Abierta',
    category: 'Abierta Varones',
    logo: 'graduation',
    primaryColor: '#7C3AED',
    secondaryColor: '#FFFFFF',
    delegate: 'Dr. Javier Villacís',
    phone: '0999990011',
  },
  {
    id: 'team-ab-10',
    name: 'Lex Pro FC',
    shortName: 'Lex Pro',
    category: 'Abierta Varones',
    logo: 'award',
    primaryColor: '#059669',
    secondaryColor: '#FDE047',
    delegate: 'Ab. Gabriel Soria',
    phone: '0990001122',
  },
  {
    id: 'team-ab-11',
    name: 'Lawyers',
    shortName: 'Lawyers Abierta',
    category: 'Abierta Varones',
    logo: 'scale',
    primaryColor: '#2563EB',
    secondaryColor: '#FFFFFF',
    delegate: 'Dr. Patricio Torres',
    phone: '0991113355',
  },
  {
    id: 'team-ab-12',
    name: 'Sanfra Legal',
    shortName: 'Sanfra Abierta',
    category: 'Abierta Varones',
    logo: 'shield',
    primaryColor: '#15803D',
    secondaryColor: '#FFFFFF',
    delegate: 'Ab. Carlos Benítez',
    phone: '0992224466',
  },
  {
    id: 'team-ab-13',
    name: 'Legal Sport',
    shortName: 'Legal Sport',
    category: 'Abierta Varones',
    logo: 'trophy',
    primaryColor: '#0284C7',
    secondaryColor: '#FFFFFF',
    delegate: 'Ab. Mateo Villacís',
    phone: '0993332211',
  },

  // ==========================================
  // CATEGORÍA: +40 VARONES (9 Equipos)
  // ==========================================
  {
    id: 'team-40-1',
    name: 'Leones Q (+40)',
    shortName: 'Leones Q +40',
    category: '+40 Varones',
    logo: 'shield',
    primaryColor: '#C2410C',
    secondaryColor: '#FFFFFF',
    delegate: 'Dr. Santiago Morales',
    phone: '0991112233',
  },
  {
    id: 'team-40-2',
    name: 'Futleg (+40)',
    shortName: 'Futleg +40',
    category: '+40 Varones',
    logo: 'gavel',
    primaryColor: '#0369A1',
    secondaryColor: '#FFFFFF',
    delegate: 'Ab. Mateo Benítez',
    phone: '0992223344',
  },
  {
    id: 'team-40-3',
    name: 'AKD (+40)',
    shortName: 'AKD +40',
    category: '+40 Varones',
    logo: 'crown',
    primaryColor: '#B91C1C',
    secondaryColor: '#FDE047',
    delegate: 'Dr. Leonardo Morales',
    phone: '0994445577',
  },
  {
    id: 'team-40-4',
    name: 'Alianza Legal (+40)',
    shortName: 'Alianza +40',
    category: '+40 Varones',
    logo: 'book',
    primaryColor: '#1E40AF',
    secondaryColor: '#FFFFFF',
    delegate: 'Dr. Byron López',
    phone: '0997778899',
  },
  {
    id: 'team-40-5',
    name: 'Boman Legal (+40)',
    shortName: 'Boman +40',
    category: '+40 Varones',
    logo: 'file-text',
    primaryColor: '#065F46',
    secondaryColor: '#FFFFFF',
    delegate: 'Ab. Andrés Sevilla',
    phone: '0998889900',
  },
  {
    id: 'team-40-6',
    name: 'Club IDUS (+40)',
    shortName: 'IDUS +40',
    category: '+40 Varones',
    logo: 'graduation',
    primaryColor: '#6D28D9',
    secondaryColor: '#FFFFFF',
    delegate: 'Dr. Javier Villacís',
    phone: '0999990011',
  },
  {
    id: 'team-40-7',
    name: 'Lawyers (+40)',
    shortName: 'Lawyers +40',
    category: '+40 Varones',
    logo: 'scale',
    primaryColor: '#1D4ED8',
    secondaryColor: '#FFFFFF',
    delegate: 'Dr. Patricio Torres',
    phone: '0991113355',
  },
  {
    id: 'team-40-8',
    name: 'Vodka Jr.',
    shortName: 'Vodka Jr.',
    category: '+40 Varones',
    logo: 'trophy',
    primaryColor: '#0369A1',
    secondaryColor: '#E0F2FE',
    delegate: 'Ab. Rodrigo Cárdenas',
    phone: '0993335577',
  },
  {
    id: 'team-40-9',
    name: 'Chamucos',
    shortName: 'Chamucos',
    category: '+40 Varones',
    logo: 'landmark',
    primaryColor: '#991B1B',
    secondaryColor: '#FEF2F2',
    delegate: 'Dr. Gonzalo Holguín',
    phone: '0994446688',
  },

  // ==========================================
  // CATEGORÍA: +50 VARONES (2 Equipos)
  // ==========================================
  {
    id: 'team-50-1',
    name: 'AKD (+50)',
    shortName: 'AKD +50',
    category: '+50 Varones',
    logo: 'crown',
    primaryColor: '#991B1B',
    secondaryColor: '#FDE047',
    delegate: 'Dr. Roberto Freire',
    phone: '0995557799',
  },
  {
    id: 'team-50-2',
    name: 'Amigos del C.A.T.',
    shortName: 'Amigos C.A.T.',
    category: '+50 Varones',
    logo: 'landmark',
    primaryColor: '#00A859',
    secondaryColor: '#DC2626',
    delegate: 'Dr. Luis Proaño',
    phone: '0996668800',
  },

  // ==========================================
  // CATEGORÍA: DAMAS (4 Equipos Oficiales)
  // ==========================================
  {
    id: 'team-da-1',
    name: 'Elite Legal',
    shortName: 'Elite Legal',
    category: 'Damas',
    logo: 'crown',
    primaryColor: '#DB2777',
    secondaryColor: '#FCE7F3',
    delegate: 'Dra. María José Paredes',
    phone: '0997779911',
  },
  {
    id: 'team-da-2',
    name: 'Bef',
    shortName: 'Bef Damas',
    category: 'Damas',
    logo: 'shield',
    primaryColor: '#9333EA',
    secondaryColor: '#F3E8FF',
    delegate: 'Dra. Andrea Carrillo',
    phone: '0998880022',
  },
  {
    id: 'team-da-3',
    name: 'Sanfra',
    shortName: 'Sanfra Damas',
    category: 'Damas',
    logo: 'scale',
    primaryColor: '#059669',
    secondaryColor: '#ECFDF5',
    delegate: 'Dra. Carla Espín',
    phone: '0999991133',
  },
  {
    id: 'team-da-4',
    name: 'Damas de la Justicia',
    shortName: 'Justicia',
    category: 'Damas',
    logo: 'gavel',
    primaryColor: '#2563EB',
    secondaryColor: '#EFF6FF',
    delegate: 'Dra. Sofia Holguín',
    phone: '0990002244',
  },
];

// Clubs (owners) with teams in more than one category. Teams sharing a clubId
// belong to the same owner, so the scheduler keeps their matches consecutive
// and never at the same time.
const CLUB_GROUPS: Record<string, string> = {
  'team-ab-1': 'club-leonesq',  'team-40-1': 'club-leonesq',
  'team-ab-2': 'club-futleg',   'team-40-2': 'club-futleg',
  'team-ab-4': 'club-akd',      'team-40-3': 'club-akd',     'team-50-1': 'club-akd',
  'team-ab-7': 'club-alianza',  'team-40-4': 'club-alianza',
  'team-ab-8': 'club-boman',    'team-40-5': 'club-boman',
  'team-ab-9': 'club-idus',     'team-40-6': 'club-idus',
  'team-ab-11': 'club-lawyers', 'team-40-7': 'club-lawyers',
  'team-ab-12': 'club-sanfra',  'team-da-3': 'club-sanfra',
};

export const INITIAL_TEAMS: Team[] = RAW_TEAMS.map((t) =>
  CLUB_GROUPS[t.id] ? { ...t, clubId: CLUB_GROUPS[t.id] } : t
);

// Producción: sin jugadores ni calendario precargados. Los jugadores se
// registran en vivo (inscripción/Admin) y el calendario se genera cuando los
// equipos estén listos.
export const INITIAL_PLAYERS: Player[] = [];

export const INITIAL_MATCHES: Match[] = [];

// Cuentas del sistema. Las CONTRASEÑAS se definen en Supabase Auth (panel), NO
// aquí. Estos registros solo asocian cada email con su rol y nombre.
export const INITIAL_USERS: User[] = [
  { id: 'u-admin-cb', name: 'Carlos Bucheli', username: 'cbucheli', role: 'ADMIN', email: 'cb@copa.com' },
  { id: 'u-admin', name: 'Administrador', username: 'admin', role: 'ADMIN', email: 'admin@copa.com' },
  { id: 'u-ref-1', name: 'Árbitro 1', username: 'arbitro1', role: 'REFEREE', refereeId: 'ref-1', email: 'arbitro1@copa.com' },
  { id: 'u-ref-2', name: 'Árbitro 2', username: 'arbitro2', role: 'REFEREE', refereeId: 'ref-2', email: 'arbitro2@copa.com' },
];
